spring:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        enable_lazy_load_no_trans: true

  datasource:
    url: jdbc:mysql://localhost:3306/tracker
    username: root
    password: welcome@123